---
- set_fact:
    cron_args: "{{ _backup_cron_freq|combine(backup_cron_freq) }}"
- name: Setup cron for backup
  become: yes
  cron:
    name: "{{ cron_args.name }}"
    job: "{{ backup_cron_backup_script_path }}"
    user: "{{ backup_cron_user }}"
    minute: "{{ cron_args.minute }}"
    hour: "{{ cron_args.hour }}"
    day: "{{ cron_args.day }}"
    weekday: "{{ cron_args.weekday }}"
    month: "{{ cron_args.month }}"
    disabled: "{{ cron_args.disabled }}"

