---
- name: Ensure that we have a backup.sh path
  become: yes
  template:
    src: backup.sh
    dest: "{{ backup_cron_backup_script_path|mandatory }}"
    owner: "{{ backup_cron_user }}"
    mode: u=rwx,g=,o=

- name: Ensure that we have a restore.sh path
  become: yes
  template:
    src: restore.sh
    dest: "{{ backup_cron_restore_script_path|mandatory }}"
    owner: "{{ backup_cron_user }}"
    mode: u=rwx,g=,o=
