---
- name: Ensure that we have required folders
  become: yes
  file:
    path: "{{ physical_backup_destination }}"
    state: directory
    owner: "{{ backup_cron_user }}"
    mode: '0755'
  when: physical_backup_destination is defined

- name: Delete existing folder at link location
  become: yes
  file:
    path: /opt/performcoop/backups
    state: absent
  when: physical_backup_destination is defined

- name: Ensure destination exists
  become: yes
  file:
    path: /opt/performcoop/backups/repo
    state: directory
    mode: '0755'
  when: physical_backup_destination is defined

- name: Ensure source exists
  become: yes
  file:
    path: "{{ physical_backup_destination }}"
    state: directory
    mode: '0755'
  when: physical_backup_destination is defined

- name: Create a symbolic link
  become: yes
  file:
    src: "{{ physical_backup_destination }}"
    dest: /opt/performcoop/backups/repo/backups
    owner: "{{ backup_cron_user }}"
    state: link
    force: yes
  when: physical_backup_destination is defined

- name: Ensure that we have a backup.sh path
  become: yes
  template:
    src: backup.sh
    dest: "{{ backup_cron_backup_script_path|mandatory }}"
    owner: "{{ backup_cron_user }}"
    mode: u=rwx,g=,o=

- name: Ensure that we have a restore.sh path
  become: yes
  template:
    src: restore.sh
    dest: "{{ backup_cron_restore_script_path|mandatory }}"
    owner: "{{ backup_cron_user }}"
    mode: u=rwx,g=,o=
